microservice-chart:
  image:
    repository: cstarucommonacr.azurecr.io/idpayadmissibilityassessor
    tag: latest
    pullPolicy: Always

  ingress:
    host: "uat01.idpay.internal.uat.cstar.pagopa.it"

  resources:
    requests:
      memory: "256Mi"
      cpu: "300m"
    limits:
      memory: "4Gi"
      cpu: "500m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envSecret:
    aks-api-url: cstar-u-weu-uat01-aks-apiserver-url
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  keyvault:
    name: "cstar-u-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  envConfig:
    JAVA_TOOL_OPTIONS: "-Xms128m -Xmx4g -javaagent:/app/applicationinsights-agent.jar -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3002 -Dcom.sun.management.jmxremote.rmi.port=3003 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
    CACHE_REFRESH_MS_RATE: "60000"
    REDIS_CACHE_ENABLED: "true"
    ANPR_C020_RESIDENCE_ASSESSMENT_PROPERTIES_SEND_TYPE: "TEST"
    #TODO Now we are using MOCK on APIM for ANPR and ISEE
    ANPR_C020_RESIDENCE_ASSESSMENT_ACCESS_TOKEN_BASE_URL: https://api-io.dev.cstar.pagopa.it/mock-ex-serv-anpr
    INPS_ISEE_CONSULTATION_BASE_URL: https://api-io.dev.cstar.pagopa.it/mock-ex-serv-inps
    #TODO Temporary External MOCK for PDND
    PDND_ACCESS_TOKEN_BASE_URL: https://uat.gateway.test.pdnd-interop.pagopa.it/authorization-server