microservice-chart:
  image:
    repository: cstarpcommonacr.azurecr.io/idpayadmissibilityassessor
    tag: latest
    pullPolicy: Always

  ingress:
    host: "prod01.idpay.internal.cstar.pagopa.it"

  resources:
    requests:
      memory: "256Mi"
      cpu: "300m"
    limits:
      memory: "4Gi"
      cpu: "500m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envSecret:
    aks-api-url: cstar-p-weu-prod01-aks-apiserver-url
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  keyvault:
    name: "cstar-p-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  envConfig:
    JAVA_TOOL_OPTIONS: "-Xms128m -Xmx4g -javaagent:/app/applicationinsights-agent.jar"
    CACHE_REFRESH_MS_RATE: "60000"
    REDIS_CACHE_ENABLED: "true"
    #TODO PROD URL?
    PDND_BASE_URL: https://auth.interop.pagopa.it
    #TODO PROD AUDIENCE?
    PDND_ACCESS_TOKEN_AUDIENCE: auth.interop.pagopa.it/client-assertion
    ANPR_ENV: prod
    ANPR_AUTH_USERID: pagopa-idpay
    ANPR_BASE_URL: https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C001-servizioNotifica/v1/anpr-service-e002
    #TODO Now we are using MOCK on APIM for ANPR and ISEE
    INPS_ISEE_CONSULTATION_BASE_URL: https://api-io.dev.cstar.pagopa.it/mock-ex-serv-inps
