microservice-chart:
  image:
    repository: cstardcommonacr.azurecr.io/idpayadmissibilityassessor
    tag: latest
    pullPolicy: Always

  ingress:
    host: "dev01.idpay.internal.dev.cstar.pagopa.it"

  resources:
    requests:
      memory: "256Mi"
      cpu: "300m"
    limits:
      memory: "4Gi"
      cpu: "500m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envSecret:
    aks-api-url: cstar-d-weu-dev01-aks-apiserver-url
    PAGOPA_PDND_CONFIGURATION_JWT_KEY: pagopa-pdnd-configuration-jwt-key
    PAGOPA_PDND_CONFIGURATION_AGID_JWT_PUB: pagopa-pdnd-configuration-jwt-pub

  keyvault:
    name: "cstar-d-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  envConfig:
    JAVA_TOOL_OPTIONS: "-Xms128m -Xmx4g -javaagent:/app/applicationinsights-agent.jar -agentlib:jdwp=transport=dt_socket,server=y,address=8001,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3002 -Dcom.sun.management.jmxremote.rmi.port=3003 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
    CACHE_REFRESH_MS_RATE: "60000"
    REDIS_CACHE_ENABLED: "true"

    #TODO set mock URL
    #PDND_BASE_URL: http://idpay-mock-microservice-chart:8080/idpay/mock/pdnd
    PDND_BASE_URL: https://auth.uat.interop.pagopa.it
    PDND_ACCESS_TOKEN_AUDIENCE: auth.uat.interop.pagopa.it/client-assertion

    #This should be removed once read from initiative
    PAGOPA_PDND_CONFIGURATION_CLIENT_ID: 5df9f218-df34-4f05-a9c4-e4a74b2a8e3f
    PAGOPA_PDND_CONFIGURATION_KID: r3ee8wZ39fxq71LinbYDgpoHeywbuzLyc4ynVldEAKY
    PAGOPA_PDND_CONFIGURATION_PURPOSE_ID: 8af4c795-8066-4407-a0b3-c95c2daefd6c

    ANPR_ENV: dev
    ANPR_AUTH_USERID: pagopa-idpay
    #TODO set mock URL
    #ANPR_BASE_URL: http://idpay-mock-microservice-chart:8080/idpay/mock/anpr
    ANPR_BASE_URL: https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND

    INPS_ISEE_CONSULTATION_BASE_URL: http://idpay-mock-microservice-chart:8080/idpay/mock/inps/soap
