microservice-chart:
  image:
    repository: cstarpcommonacr.azurecr.io/idpayadmissibilityassessor
    tag: latest
    pullPolicy: Always

  ingress:
    host: "prod01.idpay.internal.cstar.pagopa.it"

  resources:
    requests:
      memory: "768Mi"
      cpu: "150m"
    limits:
      memory: "768Mi"
      cpu: "600m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envSecret:
    aks-api-url: cstar-p-weu-prod01-aks-apiserver-url
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  keyvault:
    name: "cstar-p-idpay-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  envConfig:
    JAVA_TOOL_OPTIONS: "-Xms256m -Xmx512m -Djava.util.concurrent.ForkJoinPool.common.parallelism=7 -Dio.netty.eventLoopThreads=100 -javaagent:/app/applicationinsights-agent.jar -Dapplicationinsights.configuration.file=/mnt/file-config-external/appinsights-config/applicationinsights.json"
    CACHE_REFRESH_MS_RATE: "60000"
    REDIS_CACHE_ENABLED: "true"

    #TODO PROD URL?
    PDND_BASE_URL: https://auth.interop.pagopa.it
    #TODO PROD AUDIENCE?
    PDND_ACCESS_TOKEN_AUDIENCE: auth.interop.pagopa.it/client-assertion

    #TODO PROD values?
    #This should be removed once read from initiative
    PAGOPA_PDND_CONFIGURATION_CLIENT_ID: 5df9f218-df34-4f05-a9c4-e4a74b2a8e3f
    PAGOPA_PDND_CONFIGURATION_KID: r3ee8wZ39fxq71LinbYDgpoHeywbuzLyc4ynVldEAKY
    PAGOPA_PDND_CONFIGURATION_PURPOSE_ID: 8af4c795-8066-4407-a0b3-c95c2daefd6c

    ANPR_ENV: prod
    ANPR_AUTH_USERID: pagopa-idpay
    ANPR_BASE_URL: https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND

    #TODO Now we are using MOCK on APIM for ANPR and ISEE
    INPS_ISEE_CONSULTATION_BASE_URL: http://idpay-mock-microservice-chart:8080/idpay/mock/inps/soap
